"""Helpers for building tab navigation from configured groups."""

from __future__ import annotations

from typing import Iterable

LEADING_TABS = ["Margenes", "Recap"]
TRAILING_TABS = ["Configuracion", "Actualizacion"]


def build_tab_labels(groups: Iterable[str]) -> list[str]:
    """Return tab labels in the expected dashboard order."""
    return [*LEADING_TABS, *list(groups), *TRAILING_TABS]


def build_tab_index_map(groups: Iterable[str]) -> dict[str, int]:
    """Return an index map for tabs generated by ``build_tab_labels``."""
    return {label: idx for idx, label in enumerate(build_tab_labels(groups))}
